#!/bin/sh

BASEDIR=$(dirname "$0")

echo "Testing: ${BASEDIR}/kv-sh"

. "${BASEDIR}"/kv-sh "/tmp/.kv-test"

OK()      { echo "[  OK  ]"; }
FAILED()  { echo "[FAILED]"; }
RESULT()  { test "$?" = "0" && OK || FAILED; }

TEST_COUNT=0

# Usage: TESTCASE [description string]

TESTCASE() {
	TEST_COUNT="$(( $TEST_COUNT + 1 ))"
	printf "%3s %-50s" "${TEST_COUNT}" "${1}"
}

echo "Database: ${KV_DB_DIR}"

rm -rf "$KV_DB_DIR"

echo
echo RUN ALL TEST CASES:
echo ===================

TESTCASE 'call kvget for non-exist key should return empty'
	test "$(kvget name)" = ""
	RESULT

TESTCASE 'kvset then kvget a variable'
	kvset name "Tom"
	test "$(kvget name)" = "Tom"
	RESULT

TESTCASE 'kvset then kvset again with different value'
	kvset name "Tom"
	kvset name "Jerry"
	test "$(kvget name)" = "Jerry"
	RESULT

TESTCASE 'deleted variable should be empty'
	kvset name "hello world!"
	kvdel name
	test "$(kvget name)" = ""
	RESULT

TESTCASE 'kvdel non exist should be OK'
	kvdel name
	test "$(kvdel name 2>&1)" = ""
	RESULT

TESTCASE 'kvset without param return error'
	kvset 2>/dev/null
	test "$?" != "0"
	RESULT

TESTCASE 'kvget without param return error'
	kvget 2>/dev/null
	test "$?" != "0"
	RESULT

TESTCASE 'kvdel without param return error'
	kvdel 2>/dev/null
	test "$?" != "0"
	RESULT

TESTCASE 'kvset 3 keys/value; kvlist => line count = 3'
	kvclear
	kvset var1 value1
	kvset var2 value2
	kvset var3 value3
	test "$(kvlist | wc -l)" = "3"
	RESULT

TESTCASE 'kvset 3 keys/value; kvkeys => line count = 3'
        kvclear
        kvset var1 value1
        kvset var2 value2
        kvset var3 value3
        test "$(kvkeys | wc -l)" = "3"
        RESULT

TESTCASE 'non-exist-var => empty value => line count = 1'
	test "$(kvget non-exist-var | wc -l)"  = "1"
	RESULT

TESTCASE 'kvclear; kvlist => line count = 0'
	kvset cat Tom
	kvset mouse Jerry
	kvclear
	test "$(kvlist | wc -l)" = "0"
	RESULT

TESTCASE 'kvclear; kvkeys => line count = 0'
        kvset cat Tom
        kvset mouse Jerry
        kvclear
        test "$(kvkeys | wc -l)" = "0"
        RESULT

TESTCASE 'kvget return empty value => error code != 0'
    kvset name
    $(kvget name)
    test "$?" != "0"
    RESULT

TESTCASE 'spaces in value'
	kvset name '  phat  dam  '
	test "$(kvget name)" = '  phat  dam  '
	RESULT
	kvdel name

#more testcase here

echo
